# Generated by Django 5.2.3 on 2025-07-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMerma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=10)),
                ('porcentaje', models.FloatField()),
            ],
            options={
                'unique_together': {('sucursal', 'sector')},
            },
        ),
    ]
