# Generated by Django 5.2.3 on 2025-07-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0002_planmerma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='suc_id',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visor.region')),
            ],
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visor.zona'),
        ),
    ]
