# Generated by Django 5.2.3 on 2025-07-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0003_region_remove_sucursal_region_remove_sucursal_suc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='codigo',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
