# Generated by Django 5.2.3 on 2025-07-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visor', '0004_region_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MermaZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_mermas', models.PositiveIntegerField()),
                ('monto_mermas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidades_vendidas', models.PositiveIntegerField()),
                ('venta_sin_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_mermas_ventas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_ajuste', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_ajuste_sobre_merma', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_merma_no_ajustada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_no_ajustada_sobre_merma', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visor.zona')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mermas.sector')),
            ],
        ),
        migrations.CreateModel(
            name='MermaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_mermas', models.PositiveIntegerField()),
                ('monto_mermas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidades_vendidas', models.PositiveIntegerField()),
                ('venta_sin_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_mermas_ventas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_ajuste', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_ajuste_sobre_merma', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_merma_no_ajustada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_no_ajustada_sobre_merma', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visor.sucursal')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mermas.sector')),
            ],
        ),
    ]
