# Generated by Django 5.2.3 on 2025-07-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mermas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
