# Generated by Django 5.2.3 on 2025-07-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mermas', '0003_remove_mermasucursal_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mermasucursal',
            name='cantidad_mermas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mermazona',
            name='cantidad_mermas',
            field=models.FloatField(),
        ),
    ]
