# Generated by Django 5.2.3 on 2025-07-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mermas', '0004_alter_mermasucursal_cantidad_mermas_and_more'),
        ('visor', '0004_region_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=6)),
                ('unidades', models.FloatField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mermas.sector')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visor.sucursal')),
            ],
            options={
                'ordering': ['mes'],
                'unique_together': {('sucursal', 'sector', 'mes')},
            },
        ),
    ]
